package kotlin.reflect.jvm.internal.impl.util;

import com.taobao.weex.el.parse.Operators;
import com.taobao.weex.ui.component.WXBasicComponentType;
import io.dcloud.common.DHInterface.IApp;
import io.dcloud.common.util.PdrUtil;
import java.util.Map;
import java.util.Set;
import kotlin.TuplesKt;
import kotlin.collections.MapsKt;
import kotlin.collections.SetsKt;
import kotlin.jvm.internal.Intrinsics;
import kotlin.reflect.jvm.internal.impl.name.Name;
import kotlin.text.Regex;

/* compiled from: OperatorNameConventions.kt */
/* loaded from: classes2.dex */
public final class OperatorNameConventions {
    public static final Set<Name> ALL_BINARY_OPERATION_NAMES;
    public static final Name AND;
    public static final Set<Name> ASSIGNMENT_OPERATIONS;
    public static final Set<Name> BINARY_OPERATION_NAMES;
    public static final Set<Name> BITWISE_OPERATION_NAMES;
    public static final Name COMPARE_TO;
    public static final Regex COMPONENT_REGEX;
    public static final Name CONTAINS;
    public static final Name DEC;
    public static final Set<Name> DELEGATED_PROPERTY_OPERATORS;
    public static final Name DIV;
    public static final Name DIV_ASSIGN;
    public static final Name EQUALS;
    public static final Name GET;
    public static final Name GET_VALUE;
    public static final Name HASH_CODE;
    public static final Name HAS_NEXT;
    public static final Name INC;
    public static final OperatorNameConventions INSTANCE = new OperatorNameConventions();
    public static final Name INV;
    public static final Name INVOKE;
    public static final Name ITERATOR;
    public static final Name MINUS;
    public static final Name MINUS_ASSIGN;
    public static final Name NEXT;
    public static final Name NOT;
    public static final Set<Name> NUMBER_CONVERSIONS;
    public static final Name OR;
    public static final Name PLUS;
    public static final Name PLUS_ASSIGN;
    public static final Name PROVIDE_DELEGATE;
    public static final Name RANGE_TO;
    public static final Name RANGE_UNTIL;
    public static final Name REM;
    public static final Name REM_ASSIGN;
    public static final Name SET;
    public static final Name SET_VALUE;
    public static final Name SHL;
    public static final Name SHR;
    public static final Set<Name> SIMPLE_BINARY_OPERATION_NAMES;
    public static final Set<Name> SIMPLE_BITWISE_OPERATION_NAMES;
    public static final Set<Name> SIMPLE_UNARY_OPERATION_NAMES;
    public static final Set<Name> STATEMENT_LIKE_OPERATORS;
    public static final Name TIMES;
    public static final Name TIMES_ASSIGN;
    private static final Map<Name, String> TOKENS_BY_OPERATOR_NAME;
    public static final Name TO_BYTE;
    public static final Name TO_CHAR;
    public static final Name TO_DOUBLE;
    public static final Name TO_FLOAT;
    public static final Name TO_INT;
    public static final Name TO_LONG;
    public static final Name TO_SHORT;
    public static final Name TO_STRING;
    public static final Name UNARY_MINUS;
    public static final Set<Name> UNARY_OPERATION_NAMES;
    public static final Name UNARY_PLUS;
    public static final Name USHR;
    public static final Name XOR;

    private OperatorNameConventions() {
    }

    static {
        Name nameIdentifier = Name.identifier("getValue");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier, "identifier(...)");
        GET_VALUE = nameIdentifier;
        Name nameIdentifier2 = Name.identifier("setValue");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier2, "identifier(...)");
        SET_VALUE = nameIdentifier2;
        Name nameIdentifier3 = Name.identifier("provideDelegate");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier3, "identifier(...)");
        PROVIDE_DELEGATE = nameIdentifier3;
        Name nameIdentifier4 = Name.identifier("equals");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier4, "identifier(...)");
        EQUALS = nameIdentifier4;
        Name nameIdentifier5 = Name.identifier("hashCode");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier5, "identifier(...)");
        HASH_CODE = nameIdentifier5;
        Name nameIdentifier6 = Name.identifier("compareTo");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier6, "identifier(...)");
        COMPARE_TO = nameIdentifier6;
        Name nameIdentifier7 = Name.identifier("contains");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier7, "identifier(...)");
        CONTAINS = nameIdentifier7;
        Name nameIdentifier8 = Name.identifier("invoke");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier8, "identifier(...)");
        INVOKE = nameIdentifier8;
        Name nameIdentifier9 = Name.identifier("iterator");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier9, "identifier(...)");
        ITERATOR = nameIdentifier9;
        Name nameIdentifier10 = Name.identifier("get");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier10, "identifier(...)");
        GET = nameIdentifier10;
        Name nameIdentifier11 = Name.identifier("set");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier11, "identifier(...)");
        SET = nameIdentifier11;
        Name nameIdentifier12 = Name.identifier("next");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier12, "identifier(...)");
        NEXT = nameIdentifier12;
        Name nameIdentifier13 = Name.identifier("hasNext");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier13, "identifier(...)");
        HAS_NEXT = nameIdentifier13;
        Name nameIdentifier14 = Name.identifier("toString");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier14, "identifier(...)");
        TO_STRING = nameIdentifier14;
        COMPONENT_REGEX = new Regex("component\\d+");
        Name nameIdentifier15 = Name.identifier("and");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier15, "identifier(...)");
        AND = nameIdentifier15;
        Name nameIdentifier16 = Name.identifier("or");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier16, "identifier(...)");
        OR = nameIdentifier16;
        Name nameIdentifier17 = Name.identifier("xor");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier17, "identifier(...)");
        XOR = nameIdentifier17;
        Name nameIdentifier18 = Name.identifier("inv");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier18, "identifier(...)");
        INV = nameIdentifier18;
        Name nameIdentifier19 = Name.identifier("shl");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier19, "identifier(...)");
        SHL = nameIdentifier19;
        Name nameIdentifier20 = Name.identifier("shr");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier20, "identifier(...)");
        SHR = nameIdentifier20;
        Name nameIdentifier21 = Name.identifier("ushr");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier21, "identifier(...)");
        USHR = nameIdentifier21;
        Name nameIdentifier22 = Name.identifier("inc");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier22, "identifier(...)");
        INC = nameIdentifier22;
        Name nameIdentifier23 = Name.identifier("dec");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier23, "identifier(...)");
        DEC = nameIdentifier23;
        Name nameIdentifier24 = Name.identifier(IApp.ConfigProperty.CONFIG_PLUS);
        Intrinsics.checkNotNullExpressionValue(nameIdentifier24, "identifier(...)");
        PLUS = nameIdentifier24;
        Name nameIdentifier25 = Name.identifier("minus");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier25, "identifier(...)");
        MINUS = nameIdentifier25;
        Name nameIdentifier26 = Name.identifier("not");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier26, "identifier(...)");
        NOT = nameIdentifier26;
        Name nameIdentifier27 = Name.identifier("unaryMinus");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier27, "identifier(...)");
        UNARY_MINUS = nameIdentifier27;
        Name nameIdentifier28 = Name.identifier("unaryPlus");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier28, "identifier(...)");
        UNARY_PLUS = nameIdentifier28;
        Name nameIdentifier29 = Name.identifier("times");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier29, "identifier(...)");
        TIMES = nameIdentifier29;
        Name nameIdentifier30 = Name.identifier(WXBasicComponentType.DIV);
        Intrinsics.checkNotNullExpressionValue(nameIdentifier30, "identifier(...)");
        DIV = nameIdentifier30;
        Name nameIdentifier31 = Name.identifier("rem");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier31, "identifier(...)");
        REM = nameIdentifier31;
        Name nameIdentifier32 = Name.identifier("rangeTo");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier32, "identifier(...)");
        RANGE_TO = nameIdentifier32;
        Name nameIdentifier33 = Name.identifier("rangeUntil");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier33, "identifier(...)");
        RANGE_UNTIL = nameIdentifier33;
        Name nameIdentifier34 = Name.identifier("timesAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier34, "identifier(...)");
        TIMES_ASSIGN = nameIdentifier34;
        Name nameIdentifier35 = Name.identifier("divAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier35, "identifier(...)");
        DIV_ASSIGN = nameIdentifier35;
        Name nameIdentifier36 = Name.identifier("remAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier36, "identifier(...)");
        REM_ASSIGN = nameIdentifier36;
        Name nameIdentifier37 = Name.identifier("plusAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier37, "identifier(...)");
        PLUS_ASSIGN = nameIdentifier37;
        Name nameIdentifier38 = Name.identifier("minusAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier38, "identifier(...)");
        MINUS_ASSIGN = nameIdentifier38;
        Name nameIdentifier39 = Name.identifier("toDouble");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier39, "identifier(...)");
        TO_DOUBLE = nameIdentifier39;
        Name nameIdentifier40 = Name.identifier("toFloat");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier40, "identifier(...)");
        TO_FLOAT = nameIdentifier40;
        Name nameIdentifier41 = Name.identifier("toLong");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier41, "identifier(...)");
        TO_LONG = nameIdentifier41;
        Name nameIdentifier42 = Name.identifier("toInt");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier42, "identifier(...)");
        TO_INT = nameIdentifier42;
        Name nameIdentifier43 = Name.identifier("toChar");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier43, "identifier(...)");
        TO_CHAR = nameIdentifier43;
        Name nameIdentifier44 = Name.identifier("toShort");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier44, "identifier(...)");
        TO_SHORT = nameIdentifier44;
        Name nameIdentifier45 = Name.identifier("toByte");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier45, "identifier(...)");
        TO_BYTE = nameIdentifier45;
        UNARY_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier22, nameIdentifier23, nameIdentifier28, nameIdentifier27, nameIdentifier26, nameIdentifier18});
        SIMPLE_UNARY_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier28, nameIdentifier27, nameIdentifier26, nameIdentifier18});
        Set<Name> of = SetsKt.setOf((Object[]) new Name[]{nameIdentifier29, nameIdentifier24, nameIdentifier25, nameIdentifier30, nameIdentifier31, nameIdentifier32, nameIdentifier33});
        BINARY_OPERATION_NAMES = of;
        SIMPLE_BINARY_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier29, nameIdentifier24, nameIdentifier25, nameIdentifier30, nameIdentifier31});
        Set<Name> of2 = SetsKt.setOf((Object[]) new Name[]{nameIdentifier15, nameIdentifier16, nameIdentifier17, nameIdentifier18, nameIdentifier19, nameIdentifier20, nameIdentifier21});
        BITWISE_OPERATION_NAMES = of2;
        SIMPLE_BITWISE_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier15, nameIdentifier16, nameIdentifier17, nameIdentifier19, nameIdentifier20, nameIdentifier21});
        ALL_BINARY_OPERATION_NAMES = SetsKt.plus(SetsKt.plus((Set) of, (Iterable) of2), (Iterable) SetsKt.setOf((Object[]) new Name[]{nameIdentifier4, nameIdentifier7, nameIdentifier6}));
        Set<Name> of3 = SetsKt.setOf((Object[]) new Name[]{nameIdentifier34, nameIdentifier35, nameIdentifier36, nameIdentifier37, nameIdentifier38});
        ASSIGNMENT_OPERATIONS = of3;
        DELEGATED_PROPERTY_OPERATORS = SetsKt.setOf((Object[]) new Name[]{nameIdentifier, nameIdentifier2, nameIdentifier3});
        STATEMENT_LIKE_OPERATORS = SetsKt.plus(SetsKt.setOf(nameIdentifier11), (Iterable) of3);
        NUMBER_CONVERSIONS = SetsKt.setOf((Object[]) new Name[]{nameIdentifier39, nameIdentifier40, nameIdentifier41, nameIdentifier42, nameIdentifier44, nameIdentifier45, nameIdentifier43});
        TOKENS_BY_OPERATOR_NAME = MapsKt.mapOf(TuplesKt.to(nameIdentifier22, "++"), TuplesKt.to(nameIdentifier23, "--"), TuplesKt.to(nameIdentifier28, Operators.PLUS), TuplesKt.to(nameIdentifier27, Operators.SUB), TuplesKt.to(nameIdentifier26, Operators.AND_NOT), TuplesKt.to(nameIdentifier29, "*"), TuplesKt.to(nameIdentifier24, Operators.PLUS), TuplesKt.to(nameIdentifier25, Operators.SUB), TuplesKt.to(nameIdentifier30, "/"), TuplesKt.to(nameIdentifier31, "%"), TuplesKt.to(nameIdentifier32, PdrUtil.FILE_PATH_ENTRY_BACK), TuplesKt.to(nameIdentifier33, "..<"));
    }
}
